# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'GH Release'

description: 'Github Action for creating Github Releases'

author: 'softprops'

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  body:
    description: 'Note-worthy description of changes in release'
    required: false
  body-path:
    description: 'Path to load note-worthy description of changes in release from'
    required: false
  name:
    description: 'Gives the release a custom name. Defaults to tag name'
    required: false
  create-draft-mode:
    description: 'Creates release as draft. Defaults to false'
    required: false
  update-draft-flag:
    description: 'Updates release draft flag. Defaults to false'
    required: false
  update-draft-mode:
    description: 'Updates release as draft. Defaults to false'
    required: false
  prerelease:
    description: 'Identify the release as a prerelease. Defaults to false'
    required: false
  files:
    description: 'Newline-delimited list of path globs for asset files to upload'
    required: false

runs:
  using: 'node12'
  main: 'lib/main.js'

branding:
  color: 'green'
  icon: 'package'
